# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 640)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("#groupBox{border-image: url(:/main/bg.jpg);\n"
"border: 0px solid #42adff;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    height: 22px;\n"
"    border-radius: 8px;\n"
"    border: 0px solid;\n"
"    \n"
"    border-color: rgb(29, 211, 176);\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.227, y1:0.46, x2:0.886, y2:0.193182, stop:0 rgba(191, 189, 255, 255), stop:0.596591 rgba(131, 202, 235, 255), stop:1 rgba(159, 214, 208, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    font: 15px \"SimHei\"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(176, 208, 211, 160);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(176, 208, 211, 230);\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"border:0px solid rgb(10, 100, 10);\n"
"border-left:1px solid rgb(100, 100, 10);\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setStyleSheet("\n"
"\n"
"QTabWidget::pane {\n"
"border-top:1px solid rgba(200, 200, 100, 150);\n"
"\n"
"background: rgba(150, 100, 100, 0); \n"
"}\n"
"\n"
"\n"
"QTabBar::tab\n"
"{\n"
"    \n"
"    color: rgb(241, 241, 241);\n"
"     font: 12pt \"SimHei\";\n"
"     background-color:rgba(104,191,249,50);\n"
"     min-width: 40px;\n"
"     min-height: 30px;\n"
"     padding:1px;\n"
"\n"
"     border-top-left-radius: 8px;\n"
"     border-top-right-radius: 8px;\n"
"  \n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    margin-top:5px;\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    font: 13pt \"SimHei\";\n"
"    background-color: rgba(228, 233, 242, 50);\n"
"    \n"
"    border-top:1px solid rgb(100, 100, 10);\n"
"    border-left:1px solid rgb(100, 100, 10);\n"
"    border-right:1px solid rgb(100, 100, 10);\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgba(255, 170, 255, 50);\n"
"color: rgb(255, 255, 255);\n"
"border:0px solid rgb(10, 100, 10);\n"
"border-left:5px solid rgb(10, 100, 10);\n"
"}\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_fbg = QtWidgets.QWidget()
        self.tab_fbg.setStyleSheet("#tab_fbg{background-color: rgba(255, 255, 255, 0);}")
        self.tab_fbg.setObjectName("tab_fbg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_fbg)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ipaddress_edit = QtWidgets.QLineEdit(self.tab_fbg)
        self.ipaddress_edit.setStyleSheet("")
        self.ipaddress_edit.setObjectName("ipaddress_edit")
        self.verticalLayout_3.addWidget(self.ipaddress_edit)
        self.pushButton_fbgconfig = QtWidgets.QPushButton(self.tab_fbg)
        self.pushButton_fbgconfig.setObjectName("pushButton_fbgconfig")
        self.verticalLayout_3.addWidget(self.pushButton_fbgconfig)
        self.checkBox_fbg = QtWidgets.QCheckBox(self.tab_fbg)
        self.checkBox_fbg.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_fbg.setObjectName("checkBox_fbg")
        self.verticalLayout_3.addWidget(self.checkBox_fbg)
        self.tabWidget.addTab(self.tab_fbg, "")
        self.tab_fbga = QtWidgets.QWidget()
        self.tab_fbga.setStyleSheet("#tab_fbga{background-color: rgba(255, 255, 255, 0);}")
        self.tab_fbga.setObjectName("tab_fbga")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_fbga)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit_fbga = QtWidgets.QLineEdit(self.tab_fbga)
        self.lineEdit_fbga.setObjectName("lineEdit_fbga")
        self.verticalLayout_8.addWidget(self.lineEdit_fbga)
        self.pushButton_fbga_config = QtWidgets.QPushButton(self.tab_fbga)
        self.pushButton_fbga_config.setObjectName("pushButton_fbga_config")
        self.verticalLayout_8.addWidget(self.pushButton_fbga_config)
        self.checkBox_fbga = QtWidgets.QCheckBox(self.tab_fbga)
        self.checkBox_fbga.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_fbga.setObjectName("checkBox_fbga")
        self.verticalLayout_8.addWidget(self.checkBox_fbga)
        self.tabWidget.addTab(self.tab_fbga, "")
        self.tab_sg = QtWidgets.QWidget()
        self.tab_sg.setStyleSheet("#tab_sg{background-color: rgba(255, 255, 255, 0);}")
        self.tab_sg.setObjectName("tab_sg")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_sg)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_com = QtWidgets.QLineEdit(self.tab_sg)
        self.lineEdit_com.setStyleSheet("")
        self.lineEdit_com.setObjectName("lineEdit_com")
        self.verticalLayout_4.addWidget(self.lineEdit_com)
        self.lineEdit_com_buad = QtWidgets.QLineEdit(self.tab_sg)
        self.lineEdit_com_buad.setObjectName("lineEdit_com_buad")
        self.verticalLayout_4.addWidget(self.lineEdit_com_buad)
        self.pushButton_sgconfig = QtWidgets.QPushButton(self.tab_sg)
        self.pushButton_sgconfig.setObjectName("pushButton_sgconfig")
        self.verticalLayout_4.addWidget(self.pushButton_sgconfig)
        self.checkBox_sg = QtWidgets.QCheckBox(self.tab_sg)
        self.checkBox_sg.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_sg.setObjectName("checkBox_sg")
        self.verticalLayout_4.addWidget(self.checkBox_sg)
        self.tabWidget.addTab(self.tab_sg, "")
        self.tab_ati = QtWidgets.QWidget()
        self.tab_ati.setStyleSheet("#tab_ati{background-color: rgba(255, 255, 255, 0);}")
        self.tab_ati.setObjectName("tab_ati")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_ati)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_atigconfig = QtWidgets.QPushButton(self.tab_ati)
        self.pushButton_atigconfig.setObjectName("pushButton_atigconfig")
        self.verticalLayout_6.addWidget(self.pushButton_atigconfig)
        self.checkBox_ati = QtWidgets.QCheckBox(self.tab_ati)
        self.checkBox_ati.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_ati.setObjectName("checkBox_ati")
        self.verticalLayout_6.addWidget(self.checkBox_ati)
        self.tabWidget.addTab(self.tab_ati, "")
        self.tab_imu = QtWidgets.QWidget()
        self.tab_imu.setStyleSheet("#tab_imu{background-color: rgba(255, 255, 255, 0);}")
        self.tab_imu.setObjectName("tab_imu")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_imu)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit_imu_port = QtWidgets.QLineEdit(self.tab_imu)
        self.lineEdit_imu_port.setObjectName("lineEdit_imu_port")
        self.verticalLayout_7.addWidget(self.lineEdit_imu_port)
        self.pushButton_imuconfig = QtWidgets.QPushButton(self.tab_imu)
        self.pushButton_imuconfig.setObjectName("pushButton_imuconfig")
        self.verticalLayout_7.addWidget(self.pushButton_imuconfig)
        self.checkBox_imu = QtWidgets.QCheckBox(self.tab_imu)
        self.checkBox_imu.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_imu.setObjectName("checkBox_imu")
        self.verticalLayout_7.addWidget(self.checkBox_imu)
        self.tabWidget.addTab(self.tab_imu, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.pushButton_mark = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_mark.setObjectName("pushButton_mark")
        self.verticalLayout.addWidget(self.pushButton_mark)
        self.pushButton_start = QtWidgets.QPushButton(self.groupBox_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_start.setIcon(icon1)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout.addWidget(self.pushButton_start)
        self.checkBox_autosave = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_autosave.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_autosave.setChecked(True)
        self.checkBox_autosave.setObjectName("checkBox_autosave")
        self.verticalLayout.addWidget(self.checkBox_autosave)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_chart = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_chart.setStyleSheet("QGroupBox{\n"
"border:0px solid rgb(10, 100, 10);\n"
"\n"
"}")
        self.groupBox_chart.setTitle("")
        self.groupBox_chart.setObjectName("groupBox_chart")
        self.gridLayout.addWidget(self.groupBox_chart, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"\n"
"border:0px solid rgb(10, 100, 10);\n"
"border-bottom:1px solid rgb(100, 100, 10);\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(150, 50))
        self.label_2.setMaximumSize(QtCore.QSize(200, 80))
        self.label_2.setStyleSheet("color: rgb(255, 244, 244);\n"
"font: 75 25pt \"Roman times\";\n"
"font-weight: bold;\n"
"border-image:url(:/main/logo_transparent.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sensor Viewer"))
        self.ipaddress_edit.setText(_translate("MainWindow", "192.168.1.101:7102"))
        self.pushButton_fbgconfig.setText(_translate("MainWindow", "清零基线"))
        self.checkBox_fbg.setText(_translate("MainWindow", "采集"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fbg), _translate("MainWindow", "FBG"))
        self.lineEdit_fbga.setText(_translate("MainWindow", "192.168.0.111:4567"))
        self.pushButton_fbga_config.setText(_translate("MainWindow", "清零基线"))
        self.checkBox_fbga.setText(_translate("MainWindow", "采集"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_fbga), _translate("MainWindow", "FBGA"))
        self.lineEdit_com.setText(_translate("MainWindow", "COM3"))
        self.lineEdit_com_buad.setText(_translate("MainWindow", "38400"))
        self.pushButton_sgconfig.setText(_translate("MainWindow", "清零基线"))
        self.checkBox_sg.setText(_translate("MainWindow", "采集"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sg), _translate("MainWindow", "SG"))
        self.pushButton_atigconfig.setText(_translate("MainWindow", "清零基线"))
        self.checkBox_ati.setText(_translate("MainWindow", "采集"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ati), _translate("MainWindow", "ATI"))
        self.lineEdit_imu_port.setText(_translate("MainWindow", "COM9"))
        self.pushButton_imuconfig.setText(_translate("MainWindow", "清零基线"))
        self.checkBox_imu.setText(_translate("MainWindow", "采集"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_imu), _translate("MainWindow", "IMU"))
        self.pushButton_mark.setText(_translate("MainWindow", "标记开始"))
        self.pushButton_start.setText(_translate("MainWindow", "开始"))
        self.checkBox_autosave.setText(_translate("MainWindow", "自动保存"))
import main_rc
